# Meta Data for SEO

## Homepage
title = "ETLBox"
titleSeparator = "-"
titleAddition = "a lightweight ETL library for .NET/C#"
description = "Simple API to code ETL jobs in .NET & C#. Extremely fast data processing engine. Runs inside your applications, APIs, and jobs. Extract, filter, transform, migrate data on-the-fly."
startPage="docs/getting-started/quick-start/"

## Open Graph + Twitter Cards
images = ["logos/png/logo_etlbox_512x512.png"]
showTwitterAuthors = false
showFacebookAuthors = false
#twitterSite = "andreaslennartz"
#twitterCreator = "andreaslennartz"
#facebookAuthor = "andreas.lennartz"
#facebookPublisher = "andreas.lennartz"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo.png"
#schemaTwitter = "https://twitter.com/andreaslennartz"
schemaLinkedIn = "https://www.linkedin.com/in/andreaslennartz"
schemaGitHub = "https://github.com/etlbox"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 90
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Alert
alert = false
alertText = "New version is coming soon!"

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
