# Meta Data for SEO

## Homepage
title = "ETLBox"
titleSeparator = "-"
titleAddition = "a lightweight ETL library for .NET/C#"
description = "Simple API to code ETL jobs in .NET & C#. Extremely fast data processing engine. Runs inside your applications, APIs, and jobs. Extract, filter, transform, migrate data on-the-fly."
startPage="/docs/getting-started/quick-start/"

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["logos/png/logo_etlbox_512x512.png"]
ogLocale = "en_US"
domainTLD = "www.etlbox.net"
titleHome = "ETLBox"

## Twitter Cards
#twitterSite = "@getdoks"
#twitterCreator = "@henkverlinde"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "ETLBox"
schemaAuthor = "Andreas Lennartz"
#schemaAuthorTwitter = "https://twitter.com/henkverlinde"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/andreaslennartz"
schemaAuthorGitHub = "https://github.com/andreaslennartz"
schemaLocale = "en-US"
schemaLogo = "logos/png/logo_etlbox_512x512.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
#schemaImage, schemaImageWidth and schemaImageHeight are not rendered if schemaType = "Organization"!
#schemaImage = "doks.png"
#schemaImageWidth = 1280
#schemaImageHeight = 640
#schemaTwitter = "https://twitter.com/getdoks"
schemaLinkedIn = "https://www.linkedin.com/company/etlbox"
schemaGitHub = "https://github.com/etlbox"
#schemaSection = "blog" --not used so far

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
#footer = "Crafted with love in Berlin"

# Feed
copyRight = "Copyright (c) 2023 Andreas Lennartz"

# Alert
alert = false
alertDismissable = true
alertText = "New version out now!"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/etlbox/etlbox.website"
docsRepoBranch = "master"
docsRepoSubPath = ""
editPage = true
lastMod = false

[sections]
  sectionNav = ["docs", "recipes", "api"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = []
  searchSectionsIndex = []
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = false
  navbarSticky = true
  toTopButton = false #buggy, div container of button stretches over the full widht and overlays links on the same level
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1

[etlboxoptions]
  showCTA = true #own addition

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
