[build]
  publish = "public"
  functions = "functions"

[functions]
  directory = "assets/lambda"

[build.environment]
  NODE_VERSION = "22.12.0"
  NPM_VERSION = "11.0.0"
  HUGO_VERSION = "0.139.4"

[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build"

[context.branch-deploy]
  command = "npm run build"

[context.next]
  command = "npm run build"

[context.next.environment]
  HUGO_ENV = "next"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 1313
  port = 8888
  publish = "public"
  autoLaunch = false

# Custom headers — https://docs.netlify.com/routing/headers/#syntax-for-the-netlify-configuration-file

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; frame-src 'self' https://*.netlify.com https://*.netlify.app; manifest-src 'self' https://*.etlbox.net https://*.netlify.com https://*.netlify.app; connect-src 'self' https://*.etlbox.net https://*.algolia.net https://*.algolianet.com https://plausible.io https://*.netlify.com https://*.netlify.app; font-src 'self' https://*.etlbox.net https://*.netlify.com https://*.netlify.app; img-src 'self' https://*.etlbox.net https://*.netlify.com https://*.netlify.app https://avatars.githubusercontent.com data:; script-src 'self' 'unsafe-inline' https://*.etlbox.net https://*.algolia.net https://*.algolianet.com https://*.netlify.com https://*.netlify.app https://plausible.io 'nonce-dXNlcj0iaGVsbG8iLGRvbWFpbj0iaGVua3ZlcmxpbmRlLmNvbSIsZG9jdW1lbnQud3JpdGUodXNlcisiQCIrZG9tYWluKTs=' 'sha256-aWZ3y/RxbBYKHXH0z8+8ljrHG1mSBvyzSfxSMjBSaXk=' 'sha256-Wfb6BDd/i0sTBJm6TFHYI/RfB+SW1jx/2OZ7EqVWu2c='; style-src 'self' https://*.etlbox.net https://*.netlify.com https://*.netlify.app 'unsafe-inline'"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin"
    Permissions-Policy = "geolocation=(self), microphone=(), camera=()"
    Cache-Control= '''
    public,
    max-age=31536000'''
    Access-Control-Allow-Origin = "*"
    User-Agent = "Hugo-Netlify-Build"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

	[plugins.inputs]
    baseUrl = "https://www.etlbox.net"
    sitemapPath = "/sitemap.xml"
    ignorePeriod = 0
    providers = [
      "google",
      "yandex",
      "bing"
    ]

# Redirects and rewrites — https://docs.netlify.com/routing/redirects/#syntax-for-the-netlify-configuration-file
[[redirects]]
  from = "/demo/api/orders"
  to = "/.netlify/functions/orders"
  status = 200
  force = true

[[redirects]]
  from = "/demo/api/simple"
  to = "/.netlify/functions/simple"
  status = 200
  force = true

[[redirects]]
  from = "/book"
  to = "https://outlook.office365.com/owa/calendar/ETLBox@etlbox.net/bookings/"
  status = 302
  force = true

[[redirects]]
  from = "/servicedesk"
  to = "https://etlbox.atlassian.net/servicedesk/customer/portals"
  status = 302
  force = true

[[redirects]]
  from = "/service-desk"
  to = "https://etlbox.atlassian.net/servicedesk/customer/portals"
  status = 302
  force = true

[[redirects]]
  from = "/helpdesk"
  to = "https://etlbox.atlassian.net/servicedesk/customer/portals"
  status = 302
  force = true

[[redirects]]
  from = "/std-eula"
  to = "https://www.etlbox.net/support/eula/standard-eula/"
  status = 302
  force = true

[[redirects]]
  from = "/redist-eula"
  to = "https://www.etlbox.net/support/eula/redistribution-eula/"
  status = 302
  force = true

[[redirects]]
  from = "/nuget-license"
  to = "https://www.etlbox.net/support/eula/standard-eula/"
  status = 302
  force = true

[[redirects]]
  from = "/register-license"
  to = "https://www.etlbox.net/product/details/register-license/"
  status = 302
  force = true

[[redirects]]
  from = "/register"
  to = "https://www.etlbox.net/product/details/register-license/"
  status = 302
  force = true

[[redirects]]
  from = "/privacy-policy"
  to = "https://www.etlbox.net/support/legal-notice/#privacy-policy"
  status = 302
  force = true

[[redirects]]
  from = "/get-started"
  to = "https://www.etlbox.net/product/getting-started/welcome/"
  status = 302
  force = true

[[redirects]]
  from = "/code-examples"
  to = "https://www.etlbox.net/recipes/fundamentals/rating-orders/"
  status = 302
  force = true

[[redirects]]
  from = "/release-notes/"
  to = "https://www.etlbox.net/product/details/release-notes/"
  status = 302
  force = true
